Primera versión
elicasama/comparador-pokemon-kotlin pull request #6
Opened 2016-10-12 19:10 UTC by elicasama

2016-10-12 19:23 UTC, rodri042 commented on .gitignore
> +target/classes
Yo ignoraría las carpetas `target` y `.idea` completas

2016-10-12 19:23 UTC, rodri042 commented on .idea/compiler.xml
> +      <profile default="false" name="Maven default annotation processors profile" enabled="true">
Este borralo del repo

2016-10-12 19:23 UTC, rodri042 commented on .idea/libraries/Maven__com_google_code_gson_gson_2_2_2.xml
> +<component name="libraryTable">
Este borralo del repo

2016-10-12 19:23 UTC, rodri042 commented on .idea/libraries/Maven__org_jetbrains_kotlin_kotlin_runtime_1_0_4.xml
> +<component name="libraryTable">
Este borralo del repo

2016-10-12 19:23 UTC, rodri042 commented on .idea/libraries/Maven__org_jetbrains_kotlin_kotlin_stdlib_1_0_4.xml
> +<component name="libraryTable">
Este borralo del repo

2016-10-12 19:23 UTC, rodri042 commented on .idea/libraries/Maven__org_jetbrains_kotlin_kotlin_test_1_0_4.xml
> +<component name="libraryTable">
Este borralo del repo

2016-10-12 19:23 UTC, rodri042 commented on .idea/misc.xml
>  <?xml version="1.0" encoding="UTF-8"?>
Este borralo del repo

2016-10-12 19:23 UTC, rodri042 commented on .idea/vcs.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Este borralo del repo

2016-10-12 19:23 UTC, rodri042 commented on src/main/java/domain/PokedexOffline.kt
> + * Clase que se utiliza para evitar acceder a la api online
La mitad del comentario sobra :stuck_out_tongue: Y tampoco explica lo que hace. Ya sabemos que es una clase, y que se utiliza para algo. Yo cuando leo quiero saber qué hace (o sea, devolver pokemones que están hardcodeados a partir del nombre)

2016-10-12 19:23 UTC, rodri042 commented on src/main/java/domain/PokedexOffline.kt
> +    val gson = Gson()
Esta variable debería ser privada, no tiene sentido que la `PokedexOffline` le exponga al mundo su `gson` que usa internamente para parsear los archivos. El de afuera ni debería saber que por dentro maneja JSONs.

2016-10-12 19:23 UTC, rodri042 commented on src/main/java/domain/PokemonComparator.kt
> + * ---> byBaseExperience
Esta documentación va a quedar desactualizada en cuanto agregues otro método más de comparación. Yo pondría "Permite comparar dos pokemon por varios criterios"

2016-10-12 19:23 UTC, rodri042 commented on src/main/java/domain/PokemonComparator.kt
> +    val poke1 = PokedexOffline().getPokemonByName(poke1Name)
Estas variables deberían ser privadas (`private val poke1`)

2016-10-12 19:23 UTC, rodri042 commented on src/main/java/domain/PokemonComparator.kt
> +            return poke1
Te conviene no ser inconsistente y acá poner `this.poke1`. Item en la línea de abajo. Siempre usar el `this.` cuando te referís a variables de instancia, igual que como hacías en javascript.

2016-10-12 19:23 UTC, rodri042 commented on src/main/java/domain/PokemonComparator.kt
> + * La clase recibe los nombres de los [pokemon] a comparar
Acá usaste [pokemon] pero no hay nada que se llame pokemon como para referenciarlo

2016-10-12 19:23 UTC, rodri042 commented on src/main/java/domain/PokemonComparator.kt
> +     * Compara al [pokemon] según su estadística total
Acá usaste [pokemon] en la docu, pero no hay nada que se llame pokemon para referenciar

2016-10-12 19:23 UTC, rodri042 commented on src/main/java/domain/PokedexOffline.kt
> +    fun getTotalStat(pokemon: Pokemon): Double {
Acá hay un error groso de diseño. Decir la cantidad total de stats es responsabilidad del `Pokemon` y no de `PokedexOffline`.

Es un code smell ver que una clase recibe un objeto en cierto método, y todo lo que hace en el método es hablar con ese objeto (*¿por qué entonces no lo hace él?*).

http://ddsutn.com.ar/cursos/cursadas-anteriores/miercoles-a-la-noche-2012/seguimientoclasesmienoche2012/refactoring

Leé el que dice **Misplaced method** y si podés, todo

2016-10-12 19:23 UTC, rodri042 commented on src/main/java/domain/Stat.kt
> + * Clase que representa la estadística del [pokemon]
Acá usaste [pokemon] pero no hay nada que se llame pokemon para referenciar. Tal vez te referías a Pokemon (que es la clase). Y ahí sí

2016-10-12 19:23 UTC, rodri042 commented on src/main/java/domain/PokemonComparator.kt
> +    val poke2 = PokedexOffline().getPokemonByName(poke2Name)
Estaría bueno que no instancie a cada rato una `PokedexOffline` sino que lo haga una vez y se la guarde

2016-10-14 15:24 UTC, elicasama commented
@rodri042 ya está todo listo (creo XD), mando close? me parecía que había otro paso intermedio antes.

2016-10-14 18:29 UTC, rodri042 commented
Fijate que hay comentarios que no les diste bola, los que quedaron ("Este borralo del repo"). Solo los agregaste al git ignore, no los borraste.

`git rm {nombre del archivo o carpeta}` o algo así los va a borrar

2016-10-14 18:31 UTC, afska requested changes

2016-10-14 18:31 UTC, rodri042 commented on src/main/java/domain/PokemonComparator.kt
> +        if (pokemon.getTotalStat(this.poke1) >= pokemon.getTotalStat(this.poke2))
Nooo nooo noooo y no.

Acá estás guardando como variable a un pokemon sin datos de mentira (tu variable `pokemon`) que lo único que hace es devolver los stats totales de OTRO pokemon que recibe.

La idea de que el pokemon responda **SUS** topStats es que responda las de él, no las de otro que recibe por parámetro. Cada uno tiene que poder responder las suyas

2016-10-14 18:33 UTC, afska requested changes

2016-10-14 18:33 UTC, rodri042 commented on src/main/java/domain/PokedexOffline.kt
> +        var pokemon = gson.fromJson(pokemonBuffer, Pokemon::class.java)
Me gustaba `pokemonParseado` como nombre. No me entendiste.
Lo que te digo es que en la documentación dice [pokemon] y eso no referencia nada. Te quedó así en muchos lugares que no arreglaste también.

No tenés que usar los [] si no vas a referenciar nada (y variables dentro del método creo que no cuentan).

2016-10-14 18:34 UTC, afska requested changes

2016-10-14 18:34 UTC, rodri042 commented on src/main/java/domain/Pokemon.kt
> + * Clase Pokemon, se va a instanciar con un JSON
Clase Pokemon. Posta? XD

2016-10-14 18:35 UTC, rodri042 commented on src/main/java/domain/Pokemon.kt
> +     * Devuelve el total de estadísticas del [pokemon]
Acá por ejemplo sí tiene sentido usar `[pokemon]` porque **hay un parámetro en el método que se llama pokemon**

2016-10-19 01:56 UTC, afska requested changes

2016-10-19 01:56 UTC, rodri042 commented on src/main/java/domain/PokemonComparator.kt
> +        if (this.poke1.base_experience >= this.poke2.base_experience)
Esta lógica está repetida con el método de abajo, estaría bueno abstraerla

2016-10-19 01:56 UTC, rodri042 commented on src/main/java/domain/PokemonComparator.kt
> +    private val pokedex = PokedexOffline()
Acá no deberías hardcodear la offline, sino recibir una, guardártela y usarla :P

2016-10-19 01:58 UTC, rodri042 commented
Y hacer que el `Comparator` compare pokemon y no los tenga que ir a buscar a la pokedex

2016-10-19 18:30 UTC, afska requested changes

2016-10-19 18:30 UTC, rodri042 commented on src/main/java/domain/PokemonComparator.kt
> +    fun byBaseExperience() : Pokemon? {
No está piola que devuelva un pokemon **nullable**.

Siempre **como mínimo** el array de pokemonsAComparar debería tener dos elementos. Esto lo podrías **validar en el constructor** y **tirar una excepción** si no es así. De esta forma garantizás que siempre que le preguntes algo al comparator te lo va a responder.

2016-10-19 18:30 UTC, rodri042 commented on src/main/java/domain/PokemonComparator.kt
> +     * TODO: Sigue existiendo lógica repetida, analizar pasar el criterio por parametro
Ok pero no saques los métodos actuales. Está bueno que exponga byBaseExperience, byTotalStat, y que tmb tenga una más genérica que sea por criterio.

2016-10-19 18:30 UTC, rodri042 commented on src/main/java/domain/PokemonComparator.kt
> +class PokemonComparator ( pokemonsAComparar: ArrayList<Pokemon>) {
Te dije que las listas te conviene tiparlas siempre con la interfaz `List` y no con la implementación `ArrayList`. Acá como está ahora, si querés instanciar un `PokemonComparator` con una `LinkedList`, no podrías

2016-10-20 00:55 UTC, rodri042 commented on src/main/java/domain/Pokemons.kt
> +class Pokemons(nombresPokemon: ArrayList<String>){
Esta clase no tiene mucha razón de ser. Debería ser responsabilidad de la Pokedex, devolver muchos pokemon a partir de nombres. Es lo único que hace la Pokedex :P

2016-10-20 01:37 UTC, rodri042 commented on src/main/java/domain/Pokemons.kt
> +    val nombresDePokemon = nombresPokemon
Y aparte por qué públicos! xD

2016-10-22 19:58 UTC, afska requested changes

2016-10-22 19:58 UTC, rodri042 commented on src/main/java/domain/PokemonComparator.kt
> +     * TODO: Sigue existiendo lógica repetida, analizar pasar el criterio por parametro
Sigue existiendo lógica repetida?

2016-10-22 19:58 UTC, rodri042 commented on src/main/java/exceptions/SinSuficientesPokemon.kt
> + *
Y esto?

2016-10-22 19:58 UTC, rodri042 commented on src/main/java/domain/PokedexOffline.kt
> +    fun crearPokemons (nombresDePokemon: List <String>) : List<Pokemon> {
No sería más lógico que si el de arriba se llama `getPokemonByName` este no se llame `getPokemonByNames`?

2016-10-22 20:10 UTC, afska requested changes

2016-10-22 20:10 UTC, rodri042 commented on src/main/java/main.kt
> +    pokemons.map ({poke -> println(" ${poke.name} con ID ${poke.id} y con experiencia ${poke.base_experience}")})
Estás usando `map` para iterar, y los resultados no los usás para nada. `map` es para convertir una colección de Aes en una colección de Bs

2016-10-22 20:42 UTC, rodri042 commented on src/main/java/main.kt
> -     * TODO: Presentación de los competidores
Por experiencia base

2016-10-22 20:44 UTC, afska requested changes

2016-10-22 20:44 UTC, rodri042 commented on src/main/java/main.kt
> +     * Comparación por base de experiencia
Esto no representa la comparación por base de experiencia

(que es **experiencia base**)

2016-10-22 20:44 UTC, rodri042 commented on src/main/java/main.kt
> +     * Comparación por base de experiencia
Experiencia base

2016-10-22 20:44 UTC, rodri042 commented on src/main/java/domain/PokemonComparator.kt
> +     * Compara al [Pokemon] según su base de experiencia
Experiencia base

2016-10-22 21:20 UTC, afska requested changes

2016-10-22 21:20 UTC, rodri042 commented on src/main/java/main.kt
> +    val poke = pokemons.iterator()
Por qué un iterator? `pokemons.forEach`, como lo que vimos en javascript

2016-10-23 16:18 UTC, afska approved these changes

2016-10-23 17:05 UTC, merged